# Generated by Django 5.0.6 on 2024-06-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wholesalers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('product_image', models.ImageField(default='product.jpeg', upload_to='product-images')),
                ('price', models.IntegerField(max_length=25)),
                ('description', models.TextField(max_length=200)),
                ('wholesaler_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesalers.wholesalers')),
            ],
        ),
    ]
